### ISSUE TITLE
Tested v316

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpvr#78]
Some good news, v316 has fixed tables that would not launch for me with previous builds. There is only one outstanding issue that I have and it's the "Capture Pup" VR setting, it will not save to enabled so tables that require it like Guardians Of The Galaxy and Harry Potter will not work but all other tables with pup packs run fine now (instead of crashing) for me albeit with just the backglass and no pup pack. Also, "table reflections" looks awesome in VR :)  Thanks

**Comment by psiomicron** [comment]
We noticed we can override this by doing a regedit and editing "HKEY_CURRENT_USER\Software\Visual Pinball\VP10\Player\CapturePUP" and set it to 1. My issue is I get a red tint on pup packs and tables with B2S file is translucent. See attached pics.
![20221018_124858](https://user-images.githubusercontent.com/23017535/196532810-2882f1c1-da7f-4b73-acb3-513c77bfeda8.jpg)
![20221018_125135](https://user-images.githubusercontent.com/23017535/196532842-cc915ef2-e243-4d41-8776-cd5827529508.jpg)

**Comment by vbousquet** [comment]
As of v323, the capture settings bug should be solved. Also quite a few bugs on coloring were solved. Not the puppack though

**Comment by psiomicron** [comment]
Ok so the red tint is gone on v323 but the B2S issue still exists the
transparency issue.

**Comment by psiomicron** [comment]
Also didn't know if you mentioned this or not, but v323 the Capture Pup
button won't stay checked and have to still manually set in regedit.

**Comment by studlygoorite** [comment]
> As of v323, the capture settings bug should be solved. Also quite a few bugs on coloring were solved. Not the puppack though

I see the button (Capture Pup) now saves with v327 but the "Disable B2S" button does not save either, since it was moved to the VR Settings with v295.
Also, I just tested v327 and 4 out of 5 pup packs worked!! Just had the transparent backglass issue with Star Wars pup pack.

**Comment by studlygoorite** [comment]
The red tint is back with v333 on AC/DC and Harry Potter. Avatar, Guardians of the Galaxy and The Avengers are good though.

**Comment by studlygoorite** [comment]
v335 fixed the red tint on Harry Potter for me but it's still there with AC/DC and other pup packs above were still good but VPW's Star Wars has major issues (transparent backglass and now the playfield went white for me). Not sure if it's related but I had no ROM sounds on Bad Cats and Diner with v335, I went back to v333 and all was good, going back to v335 and the ROM sounds were good?? :)
